spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    password: 123456
  mail:
    host: smtp.qq.com
    username: 298692628@qq.com
    password: bxyitdysvzajbgdi56444
server:
  port: 8090