spring:
  rabbitmq:
    host: 118.25.26.200
  redis:
    host: 118.25.26.200
    password: 123456
  mail:
    host: smtp.qq.com
    username: 298692628@qq.com
    password: bxyitdysvzajbgdi222
server:
  port: 8090